#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

rm -rf $ZSH/sublime3/User
cp -R ~/home/sekude/.config/sublime-text-3/Packages/User
